export const data = [
  {
    role_name: 'Frontend Developer',
    company: 'TechWave Solutions',
    date_applied: '2024-12-20',
    link: 'https://techwave.jobs/frontend-developer',
    platform: 'LinkedIn',
    status: 'Under Review',
  },
  {
    role_name: 'Junior Fullstack Engineer',
    company: 'CodeCrafters Inc.',
    date_applied: '2024-12-18',
    link: 'https://codecrafters.com/jobs/junior-fullstack',
    platform: 'Company Website',
    status: 'Rejected',
  },
  {
    role_name: 'React Developer',
    company: 'Innovatech Labs',
    date_applied: '2024-12-22',
    link: 'https://innovatechlabs.com/careers/react-developer',
    platform: 'Indeed',
    status: 'Interview Scheduled',
  },
  {
    role_name: 'UX/UI Designer',
    company: 'Creative Minds Studio',
    date_applied: '2024-12-25',
    link: 'https://creativeminds.design/careers/ux-ui-designer',
    platform: 'LinkedIn',
    status: 'Awaiting Feedback',
  },
  {
    role_name: 'Software Engineer Intern',
    company: 'FutureSoft',
    date_applied: '2024-12-21',
    link: 'https://futuresoft.jobs/software-engineer-intern',
    platform: 'Glassdoor',
    status: 'Under Review',
  },
  {
    role_name: 'Web Developer',
    company: 'BrightCode Solutions',
    date_applied: '2024-12-23',
    link: 'https://brightcode.co/jobs/web-developer',
    platform: 'AngelList',
    status: 'Applied',
  },
  {
    role_name: 'Junior Frontend Developer',
    company: 'Digital Horizons',
    date_applied: '2024-12-19',
    link: 'https://digitalhorizons.com/jobs/frontend-developer',
    platform: 'LinkedIn',
    status: 'Rejected',
  },
  {
    role_name: 'Backend Developer',
    company: 'DataSync Technologies',
    date_applied: '2024-12-26',
    link: 'https://datasynctech.jobs/backend-developer',
    platform: 'Company Website',
    status: 'Awaiting Feedback',
  },
  {
    role_name: 'Fullstack Developer',
    company: 'CodeSphere',
    date_applied: '2024-12-28',
    link: 'https://codesphere.io/careers/fullstack-developer',
    platform: 'AngelList',
    status: 'Applied',
  },
  {
    role_name: 'Frontend Engineer',
    company: 'Skyline Software',
    date_applied: '2024-12-24',
    link: 'https://skyline.jobs/frontend-engineer',
    platform: 'Indeed',
    status: 'Under Review',
  },
];
