export const populate_data = [
  {
    role_name: 'Frontend Developer',
    company_name: 'Tech Corp',
    date_applied: '2025-02-01',
    link: 'https://techcorp.com/job/frontend-dev',
    description:
      'As a Frontend Developer at Tech Corp, you will be responsible for building and maintaining user interfaces using React and TypeScript. You will work closely with the design team to implement intuitive and responsive layouts. The role involves optimizing the performance of the web applications, ensuring cross-browser compatibility, and applying best practices in accessibility.',
    location: 'Remote',
    status: 'Applied',
    platform: 'LinkedIn',
  },
  {
    role_name: 'Backend Developer',
    company_name: 'DataTech',
    date_applied: '2025-01-20',
    link: 'https://datatech.com/job/backend-dev',
    description:
      'As a Backend Developer at DataTech, you will work with Node.js and PostgreSQL to create server-side applications. Your primary focus will be to design and maintain robust, scalable APIs, implement data models, and optimize database queries for performance. You will also collaborate with frontend developers to integrate with web applications and enhance the user experience.',
    location: 'Austin, USA',
    status: 'Interview Scheduled',
    platform: 'Indeed',
  },
  {
    role_name: 'Fullstack Developer',
    company_name: 'WebWorks',
    date_applied: '2025-02-10',
    link: 'https://webworks.com/job/fullstack-dev',
    description:
      'As a Fullstack Developer at WebWorks, you will work on both the frontend and backend of web applications. You will use React for the frontend and Express.js for the backend, creating end-to-end solutions. The role will involve building features, troubleshooting issues, and ensuring the scalability of applications. You will also play a key role in code reviews and mentoring junior developers.',
    location: 'Chicago, USA',
    status: 'In Review',
    platform: 'Glassdoor',
  },
  {
    role_name: 'DevOps Engineer',
    company_name: 'DeployHub',
    date_applied: '2025-02-05',
    link: 'https://deployhub.com/jobs/devops-engineer',
    description:
      'As a DevOps Engineer at DeployHub, you will be responsible for building and maintaining the infrastructure for software deployments. You will work with cloud services like AWS and Google Cloud, automate deployment pipelines using tools like Terraform and Jenkins, and ensure that systems are secure and scalable. You will also collaborate with the development team to improve system performance and uptime.',
    location: 'Remote',
    status: 'Rejected',
    platform: 'LinkedIn',
  },
  {
    role_name: 'Mobile App Developer',
    company_name: 'AppGenix',
    date_applied: '2025-02-07',
    link: 'https://appgenix.com/careers/mobile-developer',
    description:
      'As a Mobile App Developer at AppGenix, you will build and maintain mobile applications for iOS and Android using React Native. You will work closely with product managers and designers to deliver high-quality, cross-platform apps. You will also be responsible for optimizing the performance of the apps and ensuring they provide a seamless user experience.',
    location: 'New York, USA',
    status: 'Interview Scheduled',
    platform: 'AngelList',
  },
  {
    role_name: 'Cloud Engineer',
    company_name: 'CloudServe',
    date_applied: '2025-01-25',
    link: 'https://cloudserve.com/job/cloud-engineer',
    description:
      'As a Cloud Engineer at CloudServe, you will design and implement cloud infrastructure using services like AWS, Azure, or GCP. You will manage serverless architectures, monitor cloud resources, and ensure the scalability of applications. You will also be responsible for automating the deployment of cloud resources and ensuring high availability for production environments.',
    location: 'San Francisco, USA',
    status: 'In Review',
    platform: 'Hired',
  },
  {
    role_name: 'AI Engineer',
    company_name: 'FutureTech',
    date_applied: '2025-02-12',
    link: 'https://futuretech.com/careers/ai-engineer',
    description:
      'As an AI Engineer at FutureTech, you will develop machine learning models for predictive analytics, natural language processing, and computer vision. You will work with TensorFlow and PyTorch to train, evaluate, and deploy models to production. The role will involve working closely with data scientists and engineers to solve complex problems using cutting-edge AI techniques.',
    location: 'London, UK',
    status: 'Applied',
    platform: 'Company Website',
  },
  {
    role_name: 'UI/UX Designer',
    company_name: 'DesignWorks',
    date_applied: '2025-01-30',
    link: 'https://designworks.com/job/ui-ux-designer',
    description:
      'As a UI/UX Designer at DesignWorks, you will be responsible for designing engaging and user-friendly interfaces. You will collaborate with product managers and developers to create wireframes, prototypes, and high-fidelity mockups. Your work will focus on improving the user experience across web and mobile platforms, ensuring consistency and usability in all designs.',
    location: 'Berlin, Germany',
    status: 'Interview Scheduled',
    platform: 'Behance',
  },
  {
    role_name: 'Software Engineer',
    company_name: 'CodeLabs',
    date_applied: '2025-02-02',
    link: 'https://codelabs.com/jobs/software-engineer',
    description:
      'As a Software Engineer at CodeLabs, you will work on the design, development, and maintenance of software applications. You will focus on creating clean, efficient, and maintainable code in languages like JavaScript, Python, and Java. You will collaborate with other engineers and stakeholders to develop new features and ensure that the codebase remains stable and bug-free.',
    location: 'Los Angeles, USA',
    status: 'Applied',
    platform: 'LinkedIn',
  },
  {
    role_name: 'Database Administrator',
    company_name: 'DataVault',
    date_applied: '2025-01-18',
    link: 'https://datavault.com/job/database-admin',
    description:
      'As a Database Administrator at DataVault, you will manage and optimize SQL and NoSQL databases. You will be responsible for database design, performance tuning, backup strategies, and data integrity. The role also involves monitoring database health, resolving issues, and ensuring high availability for production systems.',
    location: 'Austin, USA',
    status: 'Interview Scheduled',
    platform: 'Indeed',
  },
  {
    role_name: 'Security Engineer',
    company_name: 'SecuriTech',
    date_applied: '2025-01-22',
    link: 'https://securitech.com/careers/security-engineer',
    description:
      'As a Security Engineer at SecuriTech, you will be responsible for protecting the organization’s systems and data. You will perform security audits, vulnerability assessments, and penetration testing. The role will also involve creating and implementing security policies, educating staff on security best practices, and responding to security incidents.',
    location: 'San Francisco, USA',
    status: 'In Review',
    platform: 'Glassdoor',
  },
  {
    role_name: 'Web Developer',
    company_name: 'DevSolutions',
    date_applied: '2025-02-15',
    link: 'https://devsolutions.com/careers/web-developer',
    description:
      'As a Web Developer at DevSolutions, you will be responsible for building and maintaining dynamic websites and web applications. You will work with frontend technologies like HTML, CSS, JavaScript, and frameworks such as React.js. The role includes collaborating with design and backend teams to integrate APIs and deliver a seamless user experience.',
    location: 'Los Angeles, USA',
    status: 'Applied',
    platform: 'LinkedIn',
  },
  {
    role_name: 'Frontend Engineer',
    company_name: 'WebForge',
    date_applied: '2025-02-20',
    link: 'https://webforge.com/job/frontend-engineer',
    description:
      'As a Frontend Engineer at WebForge, you will be tasked with developing interactive and responsive web pages using React.js and Next.js. You will ensure that designs are implemented faithfully and will be responsible for optimizing the performance of applications. You will also collaborate closely with UX/UI designers to ensure a high-quality user experience.',
    location: 'Remote',
    status: 'Interview Scheduled',
    platform: 'Glassdoor',
  },
  {
    role_name: 'Backend Web Developer',
    company_name: 'ByteBuilders',
    date_applied: '2025-02-18',
    link: 'https://bytebuilders.com/job/backend-web-developer',
    description:
      'As a Backend Web Developer at ByteBuilders, you will focus on building scalable and secure server-side applications using Node.js and Express.js. Your responsibilities will include designing and developing RESTful APIs, integrating with third-party services, and ensuring the security and efficiency of web applications.',
    location: 'Austin, USA',
    status: 'In Review',
    platform: 'Indeed',
  },
  {
    role_name: 'JavaScript Developer',
    company_name: 'CodeCrew',
    date_applied: '2025-02-11',
    link: 'https://codecrew.com/careers/javascript-developer',
    description:
      'As a JavaScript Developer at CodeCrew, you will work with modern JavaScript frameworks such as React and Vue.js to build complex, interactive web applications. You will be responsible for writing clean, maintainable code, collaborating with design and backend teams, and ensuring compatibility across browsers and devices.',
    location: 'New York, USA',
    status: 'Applied',
    platform: 'LinkedIn',
  },
  {
    role_name: 'Fullstack Web Developer',
    company_name: 'DevX Solutions',
    date_applied: '2025-02-08',
    link: 'https://devxsolutions.com/jobs/fullstack-web-developer',
    description:
      'As a Fullstack Web Developer at DevX Solutions, you will be responsible for both the frontend and backend development of web applications. You will work with React on the frontend and Node.js on the backend, integrating databases like MongoDB and PostgreSQL. Your goal will be to ensure the smooth operation and user-friendly design of the applications.',
    location: 'Chicago, USA',
    status: 'In Review',
    platform: 'AngelList',
  },
  {
    role_name: 'Frontend Web Developer',
    company_name: 'PixelPioneers',
    date_applied: '2025-01-30',
    link: 'https://pixelpioneers.com/careers/frontend-web-developer',
    description:
      'As a Frontend Web Developer at PixelPioneers, you will focus on building modern, responsive websites using HTML5, CSS3, and JavaScript. You will work alongside UX/UI designers to implement designs and improve the overall user experience across various platforms and devices. Experience with frameworks like Vue.js or React is required.',
    location: 'San Francisco, USA',
    status: 'Interview Scheduled',
    platform: 'Behance',
  },
  {
    role_name: 'UI Developer',
    company_name: 'WebWave',
    date_applied: '2025-01-25',
    link: 'https://webwave.com/careers/ui-developer',
    description:
      'As a UI Developer at WebWave, you will focus on implementing beautiful and functional user interfaces using HTML, CSS, and JavaScript. You will ensure the UI is responsive and optimized for various devices, while collaborating with backend developers to integrate APIs and data structures into the frontend.',
    location: 'London, UK',
    status: 'Applied',
    platform: 'Indeed',
  },
  {
    role_name: 'Web Application Developer',
    company_name: 'TechRev',
    date_applied: '2025-02-14',
    link: 'https://techrev.com/jobs/web-application-developer',
    description:
      'As a Web Application Developer at TechRev, you will be responsible for creating and maintaining web applications using frameworks like React.js and Angular. You will work on enhancing web application functionality, optimizing user interfaces, and ensuring smooth data flow between frontend and backend systems.',
    location: 'Toronto, Canada',
    status: 'In Review',
    platform: 'Glassdoor',
  },
  {
    role_name: 'E-commerce Web Developer',
    company_name: 'ShopTech',
    date_applied: '2025-02-13',
    link: 'https://shoptech.com/careers/ecommerce-web-developer',
    description:
      'As an E-commerce Web Developer at ShopTech, you will build and optimize e-commerce platforms, ensuring that online stores are functional, secure, and user-friendly. You will implement payment gateway integrations, manage product catalogs, and ensure scalability for high traffic during peak times.',
    location: 'Dallas, USA',
    status: 'Applied',
    platform: 'LinkedIn',
  },
  {
    role_name: 'WordPress Developer',
    company_name: 'WP Masters',
    date_applied: '2025-02-03',
    link: 'https://wpmaster.com/careers/wordpress-developer',
    description:
      'As a WordPress Developer at WP Masters, you will create and manage custom WordPress themes and plugins. You will collaborate with designers to implement designs and functionality, and ensure websites are fully responsive and optimized for performance. Familiarity with PHP, HTML, and CSS is required for the role.',
    location: 'Remote',
    status: 'Interview Scheduled',
    platform: 'AngelList',
  },
];
